name: Deploy to Environment

on:
  push:
    branches: [dev, staging, main]

jobs:

  deploy-dev:
    if: github.ref_name == 'dev'
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4
      - name: Show vars
        run: |
          echo "HOST=${{ vars.DEPLOY_HOST }}"
          echo "USER=${{ vars.DEPLOY_USER }}"
          echo "PATH=${{ vars.DEPLOY_PATH }}"

  deploy-staging:
    if: github.ref_name == 'staging'
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4
      - name: Show vars
        run: |
          echo "HOST=${{ vars.DEPLOY_HOST }}"
          echo "USER=${{ vars.DEPLOY_USER }}"
          echo "PATH=${{ vars.DEPLOY_PATH }}"

  deploy-prod:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - name: Show vars
        run: |
          echo "HOST=${{ vars.DEPLOY_HOST }}"
          echo "USER=${{ vars.DEPLOY_USER }}"
          echo "PATH=${{ vars.DEPLOY_PATH }}"

